In [1]:
#importing required libraries
import pandas as pd
import itertools 
from bs4 import BeautifulSoup
import requests
from requests import get
import time
from random import seed
from random import random
from random import randint

In [2]:
# specify the url format of the rental  website
url = 'https://www.pararius.com/apartments/utrecht/page-'

In [3]:
# initialize a list called houses
houses = []

# initialize variable count at 1
count = 1


# first while loop that will run 100 times 

while count <= 100:
    # initialize variable new_count at 0
    new_count = 0
    # if loop that specifies the first page separately (many websites have a first page url format different than other pages)
    if count == 1:
        first_page = 'https://www.pararius.com/apartments/utrecht/page-1'
        # request the response
        response = get(first_page)
        # parse through the html 
        html_soup = BeautifulSoup(response.text, 'html.parser')
        # in the html of the page, find all the bins with <li> and class:
        house_data = html_soup.find_all('li', class_="search-list__item search-list__item--listing")
        # I like to print where the program is on the screen so we can follow its progress and where any errors happened
        print(first_page)
        
        # if the response was not empty (if something was actually scraped)
        if house_data != []:
            # add to the list houses
            houses.extend(house_data)
            # random wait times
            value = random()
            scaled_value = 1 + (value * (9 - 5))
            print(scaled_value)
            time.sleep(scaled_value)
    # pages other than the first
    elif count != 1:
    # collect four and wait random times 
        url = 'https://www.pararius.com/apartments/utrecht/page-' + str(count)
        print(url)
        response = get(url)
        html_soup = BeautifulSoup(response.text, 'html.parser')
        print(response)
        house_data = html_soup.find_all('li', class_="search-list__item search-list__item--listing")

        if house_data != []:
            houses.extend(house_data)
            value = random()
            scaled_value = 1 + (value * (9 - 5))
            print(scaled_value)
            time.sleep(scaled_value)

        # if you get empty response, stop the loop
        else:
            print('empty')
            break
            

    count += 1

https://www.pararius.com/apartments/utrecht/page-1
1.5967755426430355
https://www.pararius.com/apartments/utrecht/page-2
<Response [200]>
4.201166573890091
https://www.pararius.com/apartments/utrecht/page-3
<Response [200]>
1.2214347356649782
https://www.pararius.com/apartments/utrecht/page-4
<Response [200]>
1.016030253643804
https://www.pararius.com/apartments/utrecht/page-5
<Response [200]>
3.7609650017413965
https://www.pararius.com/apartments/utrecht/page-6
<Response [200]>
1.0156647379094235
https://www.pararius.com/apartments/utrecht/page-7
<Response [200]>
1.3589231169666411
https://www.pararius.com/apartments/utrecht/page-8
<Response [200]>
4.7423918321679945
https://www.pararius.com/apartments/utrecht/page-9
<Response [200]>
4.305981176729329
https://www.pararius.com/apartments/utrecht/page-10
<Response [200]>
3.1769144260320172
https://www.pararius.com/apartments/utrecht/page-11
<Response [200]>
2.1273623226419
https://www.pararius.com/apartments/utrecht/page-12
<Response [200]>
3.304273431922674
https://www.pararius.com/apartments/utrecht/page-13
<Response [400]>
empty

In [4]:
len(houses)

347

In [5]:
## DATA FORMATTING 
## initializing lists and variables
count = 0
house_price = []
rental_agency = []
location = []
city = []
bedrooms = []
surface = []
## how long we are running the while loop for 
n = int(len(houses)) - 1

while count <= n:
    # running the loop through each html bin we scraped
    num = houses[int(count)]
    
    # getting the price: make sure to test this code a few times by itself to understand exactly which parameters will work 
    price = num.find_all('span',{"class":"listing-search-item__price"})[0].text
    house_price.append(price)
    df_price = pd.DataFrame({'house_price':house_price})
    df_price['house_price'] = df_price['house_price'].str.replace("\D","")
    df_price['house_price'] = df_price['house_price'].str.replace("per month","")
    
    # if you have a variable that is not present on all ads the ads, you can use try and except to avoid stopping the loop
    try:
        agency = num.find_all('a', href=True)[2].text
    except IndexError:
        agency = 'none'
    rental_agency.append(agency)
    df_agency = pd.DataFrame({'rental_agency':rental_agency})
    
   #getting the postcode: make sure to test this code a few times by itself to understand exactly which parameters will work 
    postcode = num.find('div',{"class":"listing-search-item__location"}).text
    location.append(postcode)
    df_postcode = pd.DataFrame({'postcode':location})
    df_postcode['postcode'] = df_postcode['postcode'].str.replace("\nApartment\n ","")
    df_postcode['postcode'] = df_postcode['postcode'].str.replace("\n","")
    df_postcode['postcode'] = df_postcode['postcode'].str.replace("\s","")
    df_postcode['postcode'] = df_postcode['postcode'].str.replace("               ","")
    df_postcode['postcode'] = df_postcode['postcode'].str.replace("new","")
    df_postcode['postcode'] = df_postcode['postcode'].str[0:6]
    
    #getting the number of bedrooms: make sure to test this code a few times by itself to understand exactly which parameters will work 
    bedrooms_num = num.find_all('dd',{"class":"illustrated-features__description"})[1].text
    bedrooms.append(bedrooms_num)
    df_bedrooms = pd.DataFrame({'bedrooms':bedrooms})
    df_bedrooms['bedrooms'] = df_bedrooms['bedrooms'].str.replace("\D","")
    
    #getting the sq meter size: make sure to test this code a few times by itself to understand exactly which parameters will work 
    size = num.find_all('dd',{"class":"illustrated-features__description"})[0].text
    surface.append(size)
    df_surface = pd.DataFrame({'surface':surface})
    df_surface['surface'] = df_surface['surface'].str.replace("\D","")
    
    print(count)
    
    count += 1

# concat all the different dataframes created, culminating in dfa (completed dataframe)
result = pd.concat([df_price, df_agency], axis=1, sort=False)
result2 = pd.concat([result, df_postcode], axis=1, sort=False)
result3 = pd.concat([result2, df_bedrooms], axis=1, sort=False)
df = pd.concat([result3, df_surface], axis=1, sort=False)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346

In [6]:
df.head(100)

   house_price                   rental_agency postcode bedrooms surface
0         2750                Matton Residence   3566MJ        4     151
1          800                        Prevenda   3582VA        2      30
2         1395     Stadsdaemes onroerend goed    3522XR        3      64
3         1000                       Stienstra   3544KL        3      82
4         1725                    StartHousing   3531WB        3      83
..         ...                             ...      ...      ...     ...
95         850  Borgondo Vastgoedmanagement BV   3523CL        1      28
96        1800                Rotsvast Utrecht   3512TE        2      79
97        1750                DdeG Vastgoed bv   3511ZL        3      40
98        1250                         Domvast   3571JS        2      30
99        1600                Rotsvast Utrecht   3512ED        3      68

[100 rows x 5 columns]

In [7]:
df.to_csv("rental_data_utrecht.csv",index="false")